apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "contour.fullname" . }}
  labels:
  {{- include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "contour.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "contour.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
