{{- if .Values.certgen.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "contour.fullname" . }}-certgen
  labels:
    {{- include "contour.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - create
      - get
      - put
      - post
      - patch
{{- end }}
