apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "contour.fullname" . }}-leaderelection
  labels:
    {{- include "contour.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "contour.fullname" . }}-leaderelection
subjects:
- kind: ServiceAccount
  name: {{ include "certgen.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
