apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy.fullname" . }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
  selector:
    {{- include "envoy.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  {{- if .Values.envoy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.envoy.service.loadBalancerIP }}
  {{- end }}
