{{- if .Values.certgen.enabled -}}
{{- if .Values.certgen.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certgen.serviceAccountName" . }}
  labels:
    {{- include "contour.labels" . | nindent 4 }}
  {{- with .Values.certgen.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
