{{- if .Values.envoy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy.serviceAccountName" . }}
  labels:
    {{- include "contour.labels" . | nindent 4 }}
  {{- with .Values.envoy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
